#!/bin/bash

#PBS -l nodes=1:ppn=10,walltime=2:00:00
#PBS -j oe
#PBS -m abe
#PBS -M mdb5946@psu.edu
#PBS -A wff3_a_g_hc_default

# Go to the correct place

cd $PBS_O_WORKDIR

module load python/3.6.8
module load anaconda3
source activate /storage/home/mdb5946/.conda/envs/qiime2-2020.8

#submit job from /gpfs/group/dut374/default/marcella/16s_vermivora/
#contains all samples sequences(raw_reads directory)
qiime tools import \
  --type SampleData[PairedEndSequencesWithQuality] \
  --input-path /gpfs/group/dut374/default/metabarcoding_data/221220_M07914_0088_000000000-KPRD8/ \
  --input-format CasavaOneEightSingleLanePerSampleDirFmt \
  --output-path /gpfs/group/dut374/default/marcella/16s_vermivora/demux-seqs.qza
#took ~15 mins

qiime dada2 denoise-paired \
  --p-n-threads 0 \
  --i-demultiplexed-seqs /gpfs/group/dut374/default/marcella/16s_vermivora/demux-seqs.qza \
  --p-trim-left-f 19 \
  --p-trim-left-r 20 \
  --p-trunc-len-f 245 \
  --p-trunc-len-r 245 \
  --output-dir /gpfs/group/dut374/default/marcella/16s_vermivora/denoised/ \
  --o-table feature_table.qza \
  --o-representative-sequences rep-seqs.qza \
  --o-denoising-stats denoising-stats.qza
#took ~40 mins

qiime feature-table summarize \
  --i-table feature_table.qza \
  --o-visualization feature_table.qzv

qiime feature-table tabulate-seqs \
  --i-data rep-seqs.qza \
  --o-visualization rep-seqs.qzv

qiime metadata tabulate \
  --m-input-file denoising-stats.qza \
  --o-visualization denoising-stats.qzv
